### PR TITLE
To add light mode

### PR DESCRIPTION
**Pull request by ayann07**
Issue number #20 is now fixed.
I have now adjusted the github logo , which was earlier mentioned to be changed according to the light mode.
Preview -

https://github.com/singodiyashubham87/ScrapeIt/assets/126085856/11cf0938-1ac9-4e9b-93dc-99767a74d070
  
I am contributing this under Kharagpur Winter Of Code.

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@ayann07 Why have you modified this modal size?

**Comment by singodiyashubham87** [comment]
@ayann07 Also you should always create a new branch before starting to work on the issue, working on the main branch is not recommended.

**Comment by ayann07** [comment]
I have not modified this, it was actually a conflict.

**Comment by ayann07** [comment]
Sorry for the inconvenience, this is my first open source experience, so sorry for making changes in main branch, now I will follow your suggestions.

**Comment by ayann07** [comment]
> @ayann07 Why have you modified this modal size?
> 
> 
> 
> 

Sorry for this, actually there was a conflict and when I tried to resolve that, by mistake I removed the code which was correct and kept the code  which has changed the modal size.
         So, once again sorry for inconvenience, now I have again made the suitable changes in the modal size to make it as it was earlier.

**Comment by ayann07** [comment]
> @ayann07 Also you should always create a new branch before starting to work on the issue, working on the main branch is not recommended.

Sorry for the inconvenience, this is my first open source experience, so sorry for making changes in main branch, now I will follow your suggestions.

**Comment by singodiyashubham87** [comment]
@ayann07 Not a problem, You did a great job.
Here are some tips for you from my side: 
1. Always create a new branch and name it something that refers to the issue you could have named your branch "issue-20"
2. Write meaningful commit messages, for more information read the CONTRIBUTING.md file.

Keep growing, Well Done!

**Comment by ayann07** [comment]
Thankyou, I will be looking forward to contribute more in your repository in future.

**Pull request merged**
