### PR TITLE
FEAT:Add Light Mode to the App (#20)

### LINKED ISSUE #20: [FEATURE] : Add light mode to the app
Add a button to toggle between light and dark mode in the application.

### PR DESCRIPTION
**Pull request by ramith-kulal**
Changes Made:
Implemented a light mode feature in the app.

Before:
Screenshot 2023-11-29 144414

After Changes:
Screenshot 2023-12-01 090954

Light Mode:
Screenshot 2023-12-01 091028

Screenshot 2023-12-01 091133
Screenshot 2023-12-01 091206
fixes #20

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@ramith-kulal Are you yourself satisfied with the light mode screenshot that you have attached in the PR?
It's too much in contrast and also not appealing.

**Comment by ramith-kulal** [comment]
@singodiyashubham87  do you got any preferences regarding the appearance? like the color combinations ?.

**Comment by ramith-kulal** [comment]
Made some changes with the color , also please guide me with resolving conflicts.


Screenshot 2023-12-01 205721
 
Screenshot 2023-12-01 212015

**Comment by singodiyashubham87** [comment]
@ramith-kulal Please resolve the merge conflicts.

**Comment by ramith-kulal** [comment]
idk what i did some how managed to remove conflicts hope this works.

**Comment by singodiyashubham87** [comment]
@ramith-kulal I guess you have just added the theme functionality to the landing page only, but we want it on both pages, secondly, we are using tailwind CSS for styling so kindly revert your changes from the CSS file and add equivalent tailwindcss classes on the elements themselves.

Lastly please attach a video recording of the resultant web app, showing both the pages and the theme toggle functionality.

**Comment by singodiyashubham87** [comment]
@ramith-kulal Are you still working on the issue?

**Comment by ramith-kulal** [comment]
> @ramith-kulal Are you still working on the issue?

Hey sorry I might not able to work on this for some days , you can unassign me ,thanks

**Pull request closed without merging**
