### PR TITLE
Footer alignment fixed. 

### PR DESCRIPTION
**Pull request by nepalivai**
Fix issue #60 
image

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@nepalivai Resolve the conflicts.

**Comment by nepalivai** [comment]
@singodiyashubham87 I can't find any conflicts can you please explain.

**Comment by nepalivai** [comment]
@singodiyashubham87 It's updated, waiting for review.

**Comment by singodiyashubham87** [comment]
@nepalivai LGTM!

**Pull request merged**
