### PR TITLE
Made the radio buttons mandatory, throw alert if not selected any

### LINKED ISSUE #19: [Bug]: Make selection of one of the radio buttons mandatory before scraping
If the user comes on the web app enters a URL and then clicks the Scrape button without choosing any of the radio buttons i.e. "Text-only" or "HTML" then the app gives the scraped which is not expected.

Add a check to ensure that one of the radio buttons is selected before scraping the data.

image

### PR DESCRIPTION
**Pull request by IrfanSalim**
closes #19 

image

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@IrfanSalim Can you explain explain me why you have set this button value as "false" on change instead of "true"?
image

**Comment by IrfanSalim** [comment]
We are also setting the checked attribute with the same variable hence that way, but it works as expected so far when I tested

**Comment by singodiyashubham87** [comment]
@IrfanSalim Then the question is what is the need for a checked attribute?

**Comment by IrfanSalim** [comment]
Yea I was aiming to persist the selection even after refresh but then dropped the idea, I'll remove that and push the changes.

**Comment by singodiyashubham87** [comment]
@IrfanSalim Well Done!

**Pull request merged**
