### PR TITLE
Made the radio buttons mandatory, throw alert if not selected any

### LINKED ISSUE #19: [Bug]: Make selection of one of the radio buttons mandatory before scraping
If the user comes on the web app enters a URL and then clicks the Scrape button without choosing any of the radio buttons i.e. "Text-only" or "HTML" then the app gives the scraped which is not expected.

Add a check to ensure that one of the radio buttons is selected before scraping the data.

image

### PR DESCRIPTION
**Pull request by IrfanSalim**
closes #19 

image

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@IrfanSalim I appreciate your effort but please do not make any PR until you have been assigned the issue.
If you want to work on this issue first comment on the issue and I will assign the issue to you then you can proceed further to work on the issue and make a PR.

**Comment by IrfanSalim** [comment]
@singodiyashubham87 if you can check the issue, I had commented before raising the PR

**Comment by IrfanSalim** [comment]
Further, if you want that as a rule, you should create a contributing doc mentioning that point so people will wait for you to assign it.

**Comment by singodiyashubham87** [comment]
@IrfanSalim You commented "Hey, taking this up" which is not what you should do instead you would have asked to work on the issue & get the issue assigned to you.

I'm assigning the issue to you now, you can work on it & as of the contributing file, it's a good suggestion; I'm creating a new issue regarding that, If you want to work on that issue as well then comment on that issue.

**Comment by IrfanSalim** [comment]
Noted, @singodiyashubham87 

Will consider going forward

**Pull request closed without merging**
