### PR TITLE
Fix: Text Visibility

### LINKED ISSUE #94: Text Visibility issue
if the browser is not supporting the message text is not visible...

Capture

please allow me to work on it under KWoC tag

### PR DESCRIPTION
**Pull request by AaadityaG**
Closes #94

### CODE REVIEW

**Comment by AaadityaG** [comment]
Please consider this for KWoC`23

**Comment by singodiyashubham87** [comment]
@AaadityaG 
image

**Comment by singodiyashubham87** [comment]
@AaadityaG Are you working on the issue?

**Comment by AaadityaG** [comment]
Yes but I might raise pr till tomorrow, if someone does before tommorow let them do it!

**Comment by singodiyashubham87** [comment]
@AaadityaG It's still black text, make it white.

**Pull request closed without merging**
