### PR TITLE
[FIX]: Search bar selection error.

### PR DESCRIPTION
**Pull request by nepalivai**
Fix issue #83 
image

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@nepalivai Kindly resolve the conflicts.

**Comment by nepalivai** [comment]
@singodiyashubham87 conflict resolved

**Comment by singodiyashubham87** [comment]
@nepalivai You have merged the main branch into your working branch and removed the changes you have made, add the classes again.
Merging this PR now will not make any effect as there are 0 files changed.

**Comment by nepalivai** [comment]
Hey @singodiyashubham87, very sorry for the inconvenience. you can check it out now.

**Comment by singodiyashubham87** [comment]
@nepalivai LGTM!

**Pull request merged**
