### PR TITLE
Feat/Adding gh logo which redirects to repo

### PR DESCRIPTION
**Pull request by JonnyMc94**
- This address issue #22 
- A GitHub logo has been added which redirects to this repo
Screenshot 2023-11-27 at 14 37 30

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@JonnyMc94 The button size is too large and also not responsive for small devices, Do take care of the responsiveness.
One more thing when I logged in the icon disappeared, have a look at it again.

**Comment by JonnyMc94** [comment]
> @JonnyMc94 The button size is too large and also not responsive for small devices, Do take care of the responsiveness. One more thing when I logged in the icon disappeared, have a look at it again.

No problem. Do you have a specific size you wish the logo to be? I will have a look at the other screens also

**Comment by singodiyashubham87** [comment]
@JonnyMc94 Make it 75% of the current size and it should also decrease on smaller screen sizes.

**Comment by JonnyMc94** [comment]
@singodiyashubham87  Ok, will work on this now!

**Comment by JonnyMc94** [comment]
@singodiyashubham87 still working on responsiveness

**Comment by singodiyashubham87** [comment]
@JonnyMc94 Carry on.

**Comment by singodiyashubham87** [comment]
@JonnyMc94 LGTM!
Great Work, Jonny!

**Pull request merged**
