### PR TITLE
light and dark mode toggle button added.

### LINKED ISSUE #81: [ENHACEMENT]: New light mode and dark mode  button
now
image

enhancement:
image

### PR DESCRIPTION
**Pull request by nepalivai**
closes #81

### CODE REVIEW

**Comment by singodiyashubham87** [comment]
@nepalivai Kindly provide h video to showcase the changes.

**Comment by nepalivai** [comment]
https://github.com/singodiyashubham87/ScrapeIt/assets/108126089/e594c3aa-447f-4721-a467-7f286df21368

**Comment by nepalivai** [comment]
Merge conflicts

**Comment by singodiyashubham87** [comment]
@nepalivai Okay!

**Pull request merged**
